# Generated by Django 5.2.15 on 2026-07-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Rebooked', 'Rebooked'), ('Refunded', 'Refunded'), ('Voucher Issued', 'Voucher Issued')], default='Confirmed', max_length=20),
        ),
    ]
